# Generated by Django 2.0.2 on 2018-08-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authmodel',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='authmodel',
            name='width_field',
        ),
        migrations.AddField(
            model_name='authmodel',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='authmodel',
            name='image',
            field=models.FileField(blank=True, upload_to='C:\\Users\\Kiran\\Desktop\\Coding\\Python\\RobinhoodArmy'),
        ),
    ]
