# Generated by Django 2.0.2 on 2018-08-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0002_auto_20180819_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\Kiran\\Desktop\\Coding\\Python\\RobinhoodArmy'),
        ),
    ]
