# Generated by Django 2.0.2 on 2018-08-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0003_auto_20180819_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authmodel',
            name='description',
        ),
        migrations.AlterField(
            model_name='authmodel',
            name='image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
